BEGIN;
    CREATE TABLE key (
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        data BYTEA NOT NULL
    );
COMMIT;
