name: hawloom

x-hawloom-base: &hawloom-base
  environment:
    POSTGRES_URI: ${POSTGRES_URI}
  ports:
    - "[::1]:1323:1323"
  volumes: []
  networks:
    - hawloom-net
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:1323/healthcheck"]
    interval: 5s
    timeout: 5s
    retries: 2
  restart: unless-stopped
  depends_on:
    db:
      condition: service_started
    db-migrate:
      condition: service_completed_successfully

services:
  hawloom-latest:
    <<: *hawloom-base
    image: ffsgfy/hawloom:latest
    profiles: [latest]

  hawloom-local:
    <<: *hawloom-base
    build: .
    profiles: [local]

  db-migrate:
    image: migrate/migrate:4
    command:
      - "-path=/migrations/"
      - "-database=${POSTGRES_URI}"
      - "up"
    volumes:
      - ./configs/migrations/:/migrations/
    networks:
      - hawloom-net
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - hawloom-net
    restart: unless-stopped

volumes:
  db-data: {}

networks:
  hawloom-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-hawloom
