name: hawloom

x-hawloom-base: &hawloom-base
  command: ["-c", "/etc/hawloom/config/dev.json"]
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PORT: ${POSTGRES_PORT}
  ports:
    - "0.0.0.0:22440:22440"
  volumes:
    - ./config/:/etc/hawloom/config/:ro
  networks:
    - hawloom-net
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:22440/healthcheck"]
    interval: 5s
    timeout: 5s
    retries: 3
  restart: unless-stopped
  depends_on:
    db:
      condition: service_healthy
    db-migrate:
      condition: service_completed_successfully

services:
  hawloom-latest:
    <<: *hawloom-base
    image: ffsgfy/hawloom:latest
    profiles: [latest]

  hawloom-local:
    <<: *hawloom-base
    build: .
    profiles: [local]

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - hawloom-net
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
      start_interval: 2s
    restart: unless-stopped

  db-migrate:
    image: migrate/migrate:4
    command:
      - "-path=/migrations/"
      - "-database=${POSTGRES_URI}"
      - "up"
    volumes:
      - ./db/migrations/:/migrations/:ro
    networks:
      - hawloom-net
    depends_on:
      db:
        condition: service_healthy

  sqlc:
    image: sqlc/sqlc:1.27.0
    command:
      - "diff"
    volumes:
      - ./db/:/db/:ro
      - ./internal/db/:/internal/db/
      - ./sqlc.yaml/:/sqlc.yaml/:ro

volumes:
  db-data: {}

networks:
  hawloom-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-hawloom
