// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int32            `db:"id"`
	Name         string           `db:"name"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	PasswordHash []byte           `db:"password_hash"`
}

type Key struct {
	ID        int32            `db:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	Data      []byte           `db:"data"`
}
