// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           int32     `db:"id"`
	Name         string    `db:"name"`
	CreatedAt    time.Time `db:"created_at"`
	PasswordHash []byte    `db:"password_hash"`
}

type Doc struct {
	ID           uuid.UUID `db:"id"`
	Title        string    `db:"title"`
	Flags        int32     `db:"flags"`
	CreatedBy    int32     `db:"created_by"`
	CreatedAt    time.Time `db:"created_at"`
	VordDuration int32     `db:"vord_duration"`
}

type Key struct {
	ID        int32     `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	Data      []byte    `db:"data"`
}

type Ver struct {
	ID             uuid.UUID `db:"id"`
	Doc            uuid.UUID `db:"doc"`
	VordNum        int32     `db:"vord_num"`
	Votes          int32     `db:"votes"`
	VotesUpdatedAt time.Time `db:"votes_updated_at"`
	CreatedBy      int32     `db:"created_by"`
	CreatedAt      time.Time `db:"created_at"`
	Summary        string    `db:"summary"`
	Content        string    `db:"content"`
	Diff           []byte    `db:"diff"`
}

type Vord struct {
	Doc      uuid.UUID `db:"doc"`
	Num      int32     `db:"num"`
	Flags    int32     `db:"flags"`
	StartAt  time.Time `db:"start_at"`
	FinishAt time.Time `db:"finish_at"`
}

type Vote struct {
	Ver     uuid.UUID `db:"ver"`
	Doc     uuid.UUID `db:"doc"`
	VordNum int32     `db:"vord_num"`
	Account int32     `db:"account"`
}
