// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vord.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVordZero = `-- name: CreateVordZero :exec
INSERT INTO vord (doc, num, flags, start_at, finish_at)
VALUES ($1, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

func (q *Queries) CreateVordZero(ctx context.Context, doc uuid.UUID) error {
	_, err := q.db.Exec(ctx, createVordZero, doc)
	return err
}
