name: Go

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
  
      - name: Run tests
        run: go test -v ./...
  
      - name: Build binary
        run: go build -v ./cmd/hawloom

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: hawloom
          path: ./hawloom
          retention-days: 7
          overwrite: true
