name: Main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.27.0"

      - name: Run sqlc diff
        run: sqlc diff

      - name: Build binary
        run: go build -v ./cmd/hawloom
  
      - name: Run tests
        run: go test -v ./...

  publish:
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ffsgfy/hawloom:latest
